version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=me
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - 5432
    volumes:
      - ./scripts/init-postgres/:/docker-entrypoint-initdb.d/
